import type { Metadata } from "next";
import { Geist, Geist_Mono, Lexend_Deca } from "next/font/google";
import { Navbar } from "@/components";
import { Footer } from "@/components";
import "./globals.css";
import CopyrightSection from "@/components/HomePageSections/CopyrightSection";

const lexendDeca = Lexend_Deca({
  variable: "--font-lexend-deca",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lexendDeca.className}`}
      >
        <Navbar />
        {children}
        <Footer />
        <CopyrightSection />
      </body>
    </html>
  );
}
