import Hero from "./Hero";
import StatsSection from "./StatsSection";
import FeaturesSection from "./FeaturesSection";
import LearningGoalsSection from "./LearningGoalSection";
import StatesSection from "./StatsSection";
import CopyrightSection from "./CopyrightSection";
import CoursesSection from "./CoursesSection";
import WhatYouGetSection from "./WhatYouGetSection";
import LearningStatsSection from "./LearningStatsSection";
import TestimonialsSection from "./TestimonialsSection";
import JoinLearnersSection from "./JoinLearnersSection";
export {Hero, StatsSection, FeaturesSection, LearningGoalsSection, StatesSection, CopyrightSection, CoursesSection, WhatYouGetSection, LearningStatsSection, TestimonialsSection, JoinLearnersSection};
