import Hero from "./Hero";
import StatsSection from "./StatsSection";
import FeaturesSection from "./FeaturesSection";
import TopCategoriesSection from "./LearningGoalSection";
import StatesSection from "./StatsSection";
import CopyrightSection from "./CopyrightSection";
import CoursesSection from "./CoursesSection";
import WhatYouGetSection from "./WhatYouGetSection";
import LearningStatsSection from "./LearningStatsSection";
import TestimonialsSection from "./TestimonialsSection";
import JoinLearnersSection from "./JoinLearnersSection";
import FaqSection from "./FaqSection";
import QrAppPromo from "./QrAppPromo";
import FeaturedMediaSection from "./FeaturedMediaSection";
export { Hero, StatsSection, FeaturesSection, TopCategoriesSection, StatesSection, CopyrightSection, CoursesSection, WhatYouGetSection, LearningStatsSection, TestimonialsSection, JoinLearnersSection, FaqSection, QrAppPromo, FeaturedMediaSection };
